services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret@123
      - POSTGRES_DB=bncc
    ports:
      - "5432:5432"
    volumes:
      - data_postgres:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  data_postgres: