# This is a basic workflow to help you get started with Actions
name: CI

permissions:
  contents: read

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:


jobs:
  # This workflow contains a single job called "build"
  code-quality-check:
    name: Code Quality Check
    uses: ./.github/workflows/code-quality.yml

  coverage-and-code-analyzes:
    name: Code Coverage and Code Analysis
    strategy:
      fail-fast: false
    needs:
      - code-quality-check

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 📊 Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: sumesolutions/bncc-db
          fail_ci_if_error: true
